### ISSUE TITLE
Hard coded  port 80 on CloudFoundryServer class

### ISSUE THREAD

**Issue by nicolaenicora** [spring-cloud/spring-cloud-cloudfoundry#15]
Dear,

I do have some  problems using this library on cloud foundry due to hard coded  port 80 into CloudFoundryServer class of 'spring-cloud-cloudfoundry-discovery' module.

CloudFoundryServer  constructor:
```
	super(cloudApplication.getUris().iterator().next(), 80);
```
My services on cloud foundry are all secured so I need that CloudFoundryServer  to take a configurable port in my case should be 443.

Can be the port taken from ribbon configuration defined into 'application.yml':
myservice.ribbon.IsSecure=true
myservice.ribbon.SecurePort=443

Nicolae

**Comment by spencergibb** [comment]
I'd rather the platform give us the port, though I'm not sure where to get it from. /cc @joshlong @scottfrederick @gregturn?

**Comment by scottfrederick** [comment]
@spencergibb If an app's public route is getting registered, requests to the route would go thru the CF Router. HTTPS is terminated there, or possibly in a load balancer component in front of the CF Router, so apps always see traffic on port 80. Some CF distributions (like Pivotal CF) allow an operator to disable non-HTTPS traffic to the LB, but many CF deployments will accept HTTP or HTTPS. I don't know of a distro-neutral way to find out whether HTTP traffic is allowed to the Router or not.

**Comment by spencergibb** [comment]
so some kind of configuration should be used then.
