### ISSUE TITLE
Update documentation to discovery.[username,password]

### ISSUE THREAD

**Issue by shinmyung0** [spring-cloud/spring-cloud-cloudfoundry#17]
I think the current documentation is a little outdated.

**Comment by spencergibb** [comment]
Can you point to where in the documentation is the problem?

**Comment by shinmyung0** [comment]
Oops. I'm referring to the the third paragraph from the top:

> The `spring-cloud-cloudfoundry-discovery` project provides an implementation of Spring Cloud Commons DiscoveryClient so you can `@EnableDiscoveryClient` and provide your credentials as `spring.cloud.cloudfoundry.discovery.[email,password]` and then you can use the `DiscoveryClient` directly or via a `LoadBalancerClient`

`spring.cloud.cloudfoundry.discovery.[username,password]` is the fix.

**Comment by spencergibb** [comment]
Closed via fef7d2c9a76283d5f1199e597c367eba03a9b73d
