### ISSUE TITLE
Please support auto configuration of the reactive Cloud Foundry Java Client 

### ISSUE THREAD

**Issue by joshlong** [spring-cloud/spring-cloud-cloudfoundry#21]
Right now there's support for the old [non-Reactive Cloud Foundry Java Client](https://github.com/spring-cloud/spring-cloud-cloudfoundry/blob/3aadc3579629e3d25360860e599d8ae16a28af23/spring-cloud-cloudfoundry-discovery/src/main/java/org/springframework/cloud/cloudfoundry/discovery/CloudFoundryDiscoveryClientConfiguration.java#L53). With Spring Cloud Finchley we have an ideal opportunity to support the reactive client instead. The Reactive Client is far more powerful, not to mention performant, and it has a better API. Awkwardly, it's far more tedious to configure so it would be nice to have this done for us.

**Comment by spencergibb** [comment]
:+1: chatted with @nebhale at s1p earlier

**Comment by spencergibb** [comment]
Actually there was a bit issue for this, but we wanted to do it here. Ideally in a core module so if user doesn't want discovery it won't bring in extra

**Comment by joshlong** [comment]
Right - I filed the Boot issue and im just now realizing it was declined..

**Comment by joshlong** [comment]
has the config already been extracted out into some other module besides the discovery client support in Spring Cloud?

**Comment by joshlong** [comment]
Right. It's [here](https://github.com/spring-cloud/spring-cloud-cloudfoundry/blob/3aadc3579629e3d25360860e599d8ae16a28af23/spring-cloud-cloudfoundry-discovery/src/main/java/org/springframework/cloud/cloudfoundry/discovery/CloudFoundryDiscoveryClientConfiguration.java#L53).

**Comment by joshlong** [comment]
I'm happy to update the code to the reactive variant if you like, extracting out the auto-config for the client from the auto config for the `DiscoveryClient` impl. I don't know how many were using the CF DC before, and how many, specifically, used it for the side-effect of obtaining a configured CF client, but moving to the new client would break those users. I figure this is a big release (Finchley) and so it would be appropriate to do that. I don't expect it'd impact many, though.

**Comment by spencergibb** [comment]
I think it's fine to major versions in Finchley. PRs always welcome from the great @joshlong

**Comment by joshlong** [comment]
Hi, 

Following up, [I submitted a PR](https://github.com/spring-cloud/spring-cloud-cloudfoundry/pull/22) for your consideration. It extracts the standalone reactive CF java client configuration and then reworks the Ribbon + `DiscoveryClient` bits in terms of the new client.
